'use client';
import { useEffect, useMemo, useState } from 'react';
import SaffaHeader,{useSaffaLanguage} from '../components/SaffaHeader';
import { products } from '../../lib-products';
import './cart.css';

type CartItem={slug:string;name:string;image:string;price:number;quantity:number;color?:string;arColor?:string;size?:string};
const FREE_SHIPPING_THRESHOLD=2000;
export default function CartPage(){
 const [language]=useSaffaLanguage();const [cart,setCart]=useState<CartItem[]>([]);const ar=language==='ar';
 const text=ar?{cart:'سلة التسوق',item:'منتج',items:'منتجات',remove:'حذف',total:'الإجمالي',subtotal:'قيمة المنتجات',shipping:'الشحن',clear:'إفراغ السلة',checkout:'إتمام الطلب',empty:'سلتك فارغة',continue:'متابعة التسوق',add:'اختاري منتجًا من المجموعة أولاً',free:'🎉 مبروك! الشحن مجاني',away:'متبقي',freeShipping:'للحصول على شحن مجاني',quantity:'الكمية',color:'اللون',size:'المقاس',secure:'معاينة المنتج قبل الاستلام متاحة',view:'عرض المنتج',saved:'السلة محفوظة تلقائيًا',choose:'اختاري المحافظة في إتمام الطلب لحساب الشحن'}:{cart:'Your Cart',item:'item',items:'items',remove:'Remove',total:'Total',subtotal:'Products subtotal',shipping:'Shipping',clear:'Clear Cart',checkout:'Checkout',empty:'Your cart is empty',continue:'Continue Shopping',add:'Choose a product from the collection first',free:'🎉 FREE SHIPPING UNLOCKED',away:'You’re',freeShipping:'away from FREE SHIPPING',quantity:'Quantity',color:'Color',size:'Size',secure:'Inspection available before receipt',view:'View product',saved:'Your cart is saved automatically',choose:'Choose your governorate at checkout to calculate shipping'};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('saffa-cart')||'[]') as CartItem[];setCart(saved.map(item=>{const p=products.find(x=>x.slug===item.slug);return {...item,price:p?.price??item.price,color:item.color||p?.color,arColor:item.arColor||p?.arColor};}));}catch{setCart([])}},[]);
 useEffect(()=>{try{localStorage.setItem('saffa-cart',JSON.stringify(cart));window.dispatchEvent(new CustomEvent('saffa-cart-change'));}catch{}},[cart]);
 const subtotal=useMemo(()=>cart.reduce((sum,item)=>sum+item.price*item.quantity,0),[cart]);const remaining=Math.max(FREE_SHIPPING_THRESHOLD-subtotal,0);const freeShipping=subtotal>=FREE_SHIPPING_THRESHOLD;const progress=Math.min(subtotal/FREE_SHIPPING_THRESHOLD*100,100);
 function changeQuantity(slug:string,delta:number){setCart(current=>current.map(item=>item.slug===slug?{...item,quantity:item.quantity+delta}:item).filter(item=>item.quantity>0));}
 function removeItem(slug:string){setCart(current=>current.filter(item=>item.slug!==slug));}function clearCart(){setCart([]);}
 return <main className="saffa-cart-page"><SaffaHeader active="home" cartCount={cart.reduce((sum,item)=>sum+item.quantity,0)} cartAction={()=>{}}/><section className="cart-page-inner"><div className="cart-page-heading"><span>SAFFA FASHION</span><h1>{text.cart}</h1><p>{cart.length} {cart.length===1?text.item:text.items} · {text.saved}</p></div>{!cart.length?<div className="cart-empty-state"><div>0</div><h2>{text.empty}</h2><p>{text.add}</p><a href="/grid">{text.continue} →</a></div>:<><div className={`free-shipping-card ${freeShipping?'unlocked':''}`}><div className="free-shipping-copy"><strong>{freeShipping?text.free:`${text.away} EGP ${remaining.toFixed(0)} ${text.freeShipping}`}</strong><span>{freeShipping?text.secure:`${Math.round(progress)}% ${ar?'من هدف الشحن المجاني':'toward your free-shipping goal'}`}</span></div><div className="free-shipping-bar"><i style={{width:`${progress}%`}}/></div>{!freeShipping&&<small className="shipping-note">{text.choose}</small>}</div><div className="cart-list">{cart.map(item=>{const p=products.find(x=>x.slug===item.slug);return <article className="cart-page-item" key={`${item.slug}-${item.size||''}`}><a className="cart-page-image" href={`/products/${item.slug}`} aria-label={`${text.view}: ${ar?(p?.arName||item.name):(p?.name||item.name)}`}><img src={item.image} alt={ar?(p?.arName||item.name):(p?.name||item.name)}/></a><div className="cart-page-info"><span className="cart-page-color">{ar?(item.arColor||item.color):(item.color||item.arColor)}</span><h2>{ar?(p?.arName||item.name):(p?.name||item.name)}</h2><strong>EGP {item.price.toFixed(2)}</strong><small>{text.size}: {item.size||'—'}</small><div className="cart-page-quantity"><span>{text.quantity}</span><button type="button" onClick={()=>changeQuantity(item.slug,-1)} aria-label="Decrease quantity">−</button><b>{item.quantity}</b><button type="button" onClick={()=>changeQuantity(item.slug,1)} aria-label="Increase quantity">+</button></div></div><button className="cart-page-remove" type="button" onClick={()=>removeItem(item.slug)}>{text.remove}</button></article>})}</div><div className="cart-page-total"><div><span>{text.subtotal}</span><strong>EGP {subtotal.toFixed(2)}</strong></div><small>{freeShipping?text.free:text.shipping+' '+text.choose}</small></div><div className="cart-page-actions"><a className="cart-whatsapp" href="/checkout">{text.checkout} →</a><button className="cart-clear" type="button" onClick={clearCart}>{text.clear}</button></div></>}</section><a className="cart-floating-whatsapp" href="https://wa.me/201069473693" target="_blank" rel="noreferrer">💬 <span>WhatsApp</span></a></main>;
}
