export type Product = {
  slug: string; name: string; arName: string; color: string; arColor: string; image: string; description: string; arDescription: string;
  gallery?: string[];
  video?: string;
};
export const products: Product[] = [
 {slug:'mocha-grace',name:'Safa Mocha Grace Dress',arName:'فستان صفا موكا جريس',color:'Mocha Brown',arColor:'بني موكا',image:'/products/safa-mocha.png',description:'An elegant full-length modest dress in mocha brown, featuring a soft crinkled wavy texture, a gathered waist and a graceful flowing silhouette. Designed for comfortable coverage and an effortlessly elegant hijab-friendly look.',arDescription:'فستان محتشم أنيق بطول كامل باللون البني الموكا، يتميز بقماش مكرمش مموج ناعم وخصر مجمع وقصة انسيابية. يمنحك تغطية مريحة وإطلالة أنثوية راقية ومتناسقة مع الحجاب.'},
 {slug:'olive-flow',name:'Safa Olive Flow Dress',arName:'فستان صفا الزيتي المنسدل',color:'Olive Green',arColor:'أخضر زيتي',image:'/products/safa-olive.png',description:'A distinctive olive-green modest maxi dress with a soft crinkled wavy texture and flowing full-length silhouette. Comfortable, elegant and modern for the everyday hijabi wardrobe.',arDescription:'فستان ماكسي محتشم مميز باللون الأخضر الزيتي، بقماش مكرمش مموج ناعم وقصة انسيابية بطول كامل. يجمع بين الراحة والأناقة والطابع العصري.'},
 {slug:'sky-breeze',name:'Safa Sky Breeze Dress',arName:'فستان صفا النسمة السماوية',color:'Sky Blue',arColor:'أزرق سماوي',image:'/products/safa-sky.png',description:'A refreshing sky-blue modest maxi dress with a soft crinkled wavy texture and graceful flowing shape. Light, feminine and effortlessly modest.',arDescription:'فستان ماكسي محتشم باللون الأزرق السماوي المنعش، يتميز بقماش مكرمش مموج وقصة انسيابية تمنحك إطلالة خفيفة وأنثوية وراقية.'},
 {slug:'burgundy-elegance',name:'Safa Burgundy Elegance Dress',arName:'فستان صفا العنابي الأنيق',color:'Burgundy',arColor:'عنابي',image:'/products/safa-burgundy.png',description:'A rich burgundy full-length modest dress with a soft crinkled wavy texture, gathered waist and flowing skirt. A polished choice for everyday wear and special occasions.',arDescription:'فستان محتشم بطول كامل باللون العنابي الغني، بقماش مكرمش مموج وخصر مجمع وتنورة انسيابية. اختيار راقٍ للإطلالات اليومية والمناسبات.'},
 {slug:'ivory-grace',name:'Safa Ivory Grace Dress',arName:'فستان صفا العاجي الراقي',color:'Ivory',arColor:'عاجي',image:'/products/safa-ivory.png',description:'A timeless ivory modest dress with a delicate soft crinkled wavy texture and graceful flowing silhouette. Clean, feminine and elegant for the modern hijabi.',arDescription:'فستان محتشم أنيق باللون العاجي، يتميز بملمس مكرمش مموج ناعم وقصة انسيابية راقية. تصميم بسيط وأنثوي وأنيق للمرأة المحجبة.'},
 {slug:'teal-flow',name:'Safa Teal Flow Dress',arName:'فستان صفا التركوازي المنسدل',color:'Deep Teal',arColor:'تركوازي داكن',image:'/products/safa-teal.png',description:'A sophisticated deep-teal modest maxi dress with a beautiful crinkled wavy texture and flowing full-length design. Elegant coverage with a comfortable fit.',arDescription:'فستان ماكسي محتشم راقٍ باللون التركوازي الداكن، بقماش مكرمش مموج وقصة انسيابية بطول كامل. يجمع بين الاحتشام والأناقة والراحة.'},
 {slug:'rose-layer',name:'Safa Rose Layered Dress',arName:'فستان صفا الوردي بطبقات',color:'Soft Rose',arColor:'وردي هادئ',image:'/products/safa-pink.png',description:'A modern soft-rose modest dress with a distinctive layered silhouette and a beautiful flowing full-length shape. A graceful statement piece for contemporary modest fashion.',arDescription:'فستان محتشم عصري باللون الوردي الهادئ، يتميز بقصة بطبقات وشكل انسيابي بطول كامل. قطعة أنيقة ولافتة للأزياء المحتشمة العصرية.'},
 {slug:'botanical-blue',name:'Safa Botanical Dress',arName:'فستان صفا بوتانيكال',color:'Botanical Blue',arColor:'أزرق بوتاني',image:'/products/safa-botanical-blue.png',description:'A graceful full-length modest shirt dress with a delicate white botanical print on a soft botanical-blue base. Finished with a button-front design, long sleeves and an elegant flowing silhouette.',arDescription:'فستان محتشم طويل بتصميم قميص أنيق ونقوش نباتية بيضاء رقيقة على لون أزرق بوتاني هادئ، مع أزرار أمامية وأكمام طويلة وقصة انسيابية.'},
 {slug:'botanical-sky',name:'Safa Botanical Dress',arName:'فستان صفا بوتانيكال',color:'Sky Blue',arColor:'أزرق سماوي',image:'/products/safa-botanical-sky.png',description:'A graceful full-length modest shirt dress with a delicate white botanical print on a fresh sky-blue base, featuring a button-front design and flowing silhouette.',arDescription:'فستان محتشم طويل بنقوش نباتية بيضاء رقيقة على لون أزرق سماوي منعش، مع أزرار أمامية وقصة انسيابية راقية.'},
 {slug:'botanical-plum',name:'Safa Botanical Dress',arName:'فستان صفا بوتانيكال',color:'Plum',arColor:'برقوقي',image:'/products/safa-botanical-plum.png',description:'A rich plum modest maxi shirt dress decorated with an elegant white botanical print, long sleeves and a polished button-front silhouette.',arDescription:'فستان ماكسي محتشم باللون البرقوقي الغني مع نقوش نباتية بيضاء أنيقة، وأكمام طويلة وتصميم أزرار أمامي راقٍ.'},
 {slug:'botanical-lilac',name:'Safa Botanical Dress',arName:'فستان صفا بوتانيكال',color:'Lilac',arColor:'ليلكي',image:'/products/safa-botanical-lilac.png',description:'A soft lilac full-length modest shirt dress with a delicate white botanical print, long sleeves and an effortless flowing shape.',arDescription:'فستان محتشم طويل باللون الليلكي الهادئ مع نقوش نباتية بيضاء رقيقة وأكمام طويلة وقصة انسيابية.'},
 {slug:'botanical-taupe',name:'Safa Botanical Dress',arName:'فستان صفا بوتانيكال',color:'Taupe',arColor:'تاوب',image:'/products/safa-botanical-taupe.png',description:'A refined taupe modest maxi shirt dress with a delicate white botanical print, button-front styling and an elegant flowing silhouette.',arDescription:'فستان ماكسي محتشم باللون التاوب الراقي مع نقوش نباتية بيضاء رقيقة، وأزرار أمامية وقصة انسيابية أنيقة.'}
];
export const SIZE_INFO = { L:'50–75 kg', XL:'75–110 kg' } as const;
export const PRICE = 700;
