'use client';
import { useState } from 'react';
import { products, PRICE, SIZE_INFO } from '../../lib-products';

export default function ContactPage(){
 const [product,setProduct]=useState(products[0].slug); const [size,setSize]=useState<'L'|'XL'>('L'); const [weight,setWeight]=useState('');
 const p=products.find(x=>x.slug===product)!;
 const message=`Hello Saffa Fashion, I would like to order:\n\nProduct: ${p.name}\nArabic: ${p.arName}\nColor: ${p.color} / ${p.arColor}\nPrice: ${PRICE} EGP\nSize: ${size}\nWeight: ${weight || 'Not provided'} kg\n\nPlease confirm availability and delivery details.`;
 const whatsapp='https://api.whatsapp.com/message/3RRGEUO5XNISD1?autoload=1&app_absent=0';
 const send=()=>{navigator.clipboard?.writeText(message); window.open(whatsapp,'_blank');};
 return <main className="contact"><div className="container"><div className="section-head"><div><div className="kicker">Saffa Fashion</div><h1 className="serif" style={{fontSize:'clamp(42px,7vw,72px)',margin:'10px 0'}}>Contact Us</h1></div><div className="section-sub arabic">تواصلي معنا واطلبي الفستان مباشرة عبر واتساب.</div></div><div className="contact-grid"><div className="contact-card"><h3>Place your order</h3><p>Choose your product and size. Your complete order message will be prepared automatically.</p><label className="option-label">Product / المنتج</label><select value={product} onChange={e=>setProduct(e.target.value)} style={{width:'100%',padding:'14px',border:'1px solid var(--line)',borderRadius:14,background:'#fff'}}>{products.map(x=><option value={x.slug} key={x.slug}>{x.name} — {x.color}</option>)}</select><label className="option-label">Size / المقاس</label><div className="size-row">{(['L','XL'] as const).map(s=><button key={s} onClick={()=>setSize(s)} className={`size-btn ${size===s?'active':''}`}><strong>{s}</strong><br/><small>{SIZE_INFO[s]}</small></button>)}</div><label className="option-label">Weight / الوزن (optional)</label><input value={weight} onChange={e=>setWeight(e.target.value)} placeholder="e.g. 68" style={{width:'100%',padding:'14px 16px',border:'1px solid var(--line)',borderRadius:14,background:'#fff'}}/><div className="weight-box"><strong>{p.name}</strong><br/>{p.arName}<br/>Color: {p.color}<br/>Price: {PRICE.toLocaleString()} EGP<br/>Size: {size} · {SIZE_INFO[size]}</div><div className="order-box"><button className="order-btn" onClick={send}>Send Order on WhatsApp · إرسال الطلب</button><div className="note">The order message is copied to your clipboard and your WhatsApp chat opens. Paste/send the message to complete the order.</div></div></div><div className="contact-card"><h3>Connect with Saffa</h3><p>For questions, availability, delivery or anything else, contact us through your preferred platform.</p><div className="contact-links"><a className="contact-link" href={whatsapp} target="_blank"><span>WhatsApp</span><span>Chat →</span></a><a className="contact-link" href="https://www.instagram.com/_saffa_01" target="_blank"><span>Instagram</span><span>@_saffa_01 →</span></a><a className="contact-link" href="https://www.tiktok.com/@saffa_0190" target="_blank"><span>TikTok</span><span>@saffa_0190 →</span></a></div><div style={{marginTop:30}} className="arabic"><h3>معلومات المقاسات</h3><p>متوفر بمقاسين فقط:</p><p><strong>L</strong> — من 50 إلى 75 كجم<br/><strong>XL</strong> — من 75 إلى 110 كجم</p><p>جميع الفساتين بسعر <strong>{PRICE.toLocaleString()} جنيه مصري</strong>.</p></div></div></div></div></main>;
}
