'use client';
import { useEffect, useMemo, useState } from 'react';
import { products } from '../../lib-products';
import './checkout.css';

type CartItem={slug:string;name:string;image:string;price:number;quantity:number;size?:string;color?:string;arColor?:string};
const WHATSAPP_NUMBER='201069473693';
const STORE_URL='https://saffafashion.shop';
function makeOrderNumber(){const key='saffa-order-seq';const n=Number(localStorage.getItem(key)||'0')+1;localStorage.setItem(key,String(n));const d=new Date();const stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `SF-${stamp}-${String(n).padStart(4,'0')}`;}
export default function CheckoutPage(){
 const [cart,setCart]=useState<CartItem[]>([]);const [language,setLanguage]=useState<'en'|'ar'>('en');const [submitted,setSubmitted]=useState(false);const [orderNumber,setOrderNumber]=useState('');const [inspection,setInspection]=useState(true);const [customer,setCustomer]=useState({name:'',phone:'',address:''});const ar=language==='ar';
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('saffa-cart')||'[]') as CartItem[];setCart(saved.map(item=>{const p=products.find(x=>x.slug===item.slug);return {...item,price:p?.price??item.price,color:item.color||p?.color,arColor:item.arColor||p?.arColor};}));}catch{setCart([])}},[]);
 const subtotal=useMemo(()=>cart.reduce((sum,item)=>sum+item.price*item.quantity,0),[cart]);
 function placeOrder(){
  if(!cart.length)return;
  if(!customer.name.trim()||!customer.phone.trim()||!customer.address.trim()){window.alert(ar?'من فضلك اكتب الاسم ورقم الهاتف والعنوان أولاً.':'Please enter your name, phone number and address first.');return;}
  const number=makeOrderNumber();setOrderNumber(number);
  const lines=cart.map(item=>{const p=products.find(x=>x.slug===item.slug);const name=ar?(p?.arName||item.name):item.name;const color=ar?(item.arColor||p?.arColor||'غير محدد'):(item.color||p?.color||'Not specified');const image=`${STORE_URL}${item.image}`;return `• ${name}\n  ${ar?'اللون المحدد':'SELECTED COLOR'}: ${color}\n  ${ar?'المقاس':'Size'}: ${item.size||'Not specified'}\n  ${ar?'الكمية':'Quantity'}: ${item.quantity}\n  ${ar?'السعر':'Price'}: EGP ${item.price.toFixed(2)}\n  ${ar?'صورة المنتج':'Product image'}: ${image}`;}).join('\n\n');
  const message=ar?`مرحباً صفا فاشن 👋\n\nرقم الطلب: ${number}\n\nأرغب في تأكيد الطلب:\n\n${lines}\n\nالإجمالي: EGP ${subtotal.toFixed(2)}\n\nالاسم: ${customer.name}\nرقم الهاتف: ${customer.phone}\nالعنوان: ${customer.address}\nالمعاينة قبل الاستلام: ${inspection?'نعم':'لا'}\n\nيرجى تأكيد التوفر والديبوزيت والتوصيل عبر واتساب.`:`Hello Saffa Fashion 👋\n\nORDER NUMBER: ${number}\n\nI would like to confirm my order:\n\n${lines}\n\nTotal: EGP ${subtotal.toFixed(2)}\n\nName: ${customer.name}\nPhone: ${customer.phone}\nAddress: ${customer.address}\nInspection before receipt: ${inspection?'YES':'NO'}\n\nPlease confirm availability, deposit and delivery on WhatsApp.`;
  setSubmitted(true);window.location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
 }
 return <main className="saffa-checkout" dir={ar?'rtl':'ltr'}><section className="checkout-form-side"><header className="checkout-brand"><a href="/">Saffa Fashion</a><a href="/cart">{ar?'العودة للسلة':'Return to cart'}</a></header><div className="checkout-inner"><div style={{display:'flex',gap:8,marginBottom:24}}><button type="button" onClick={()=>setLanguage('en')}>English</button><button type="button" onClick={()=>setLanguage('ar')}>العربية</button></div><section><h2>{ar?'بيانات العميل':'Customer details'}</h2><label>{ar?'الاسم':'Name'}<input required value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>{ar?'رقم الهاتف':'Phone'}<input required value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} inputMode="tel" placeholder="01xxxxxxxxx"/></label><label>{ar?'العنوان':'Address'}<input required value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></label></section><label style={{display:'flex',gap:10,alignItems:'center',margin:'24px 0'}}><input type="checkbox" checked={inspection} onChange={e=>setInspection(e.target.checked)} style={{width:18,height:18}}/><span>{ar?'متاح المعاينة قبل الاستلام':'Inspection before receipt'}</span></label><button className="pay-now" onClick={placeOrder}>{submitted?(ar?`تم تجهيز الطلب ${orderNumber}`:`Order ${orderNumber} prepared`):(ar?`تأكيد الطلب · EGP ${subtotal.toFixed(2)}`:`Confirm Order · EGP ${subtotal.toFixed(2)}`)}</button><p className="checkout-note">{ar?'لا يوجد دفع كامل بالبطاقة هنا. الديبوزيت والتأكيد النهائي يتمان عبر واتساب.':'No full card payment is taken here. Deposit and final confirmation are handled through WhatsApp.'}</p></div></section><aside className="checkout-summary"><div className="summary-inner"><span className="summary-eyebrow">SAFFA FASHION</span><h1>{ar?'ملخص الطلب':'Order summary'}</h1>{orderNumber&&<p><strong>{ar?'رقم الطلب':'Order number'}: {orderNumber}</strong></p>}{!cart.length?<p>{ar?'السلة فارغة.':'Your cart is empty.'}</p>:<div className="summary-items">{cart.map(item=>{const p=products.find(x=>x.slug===item.slug);return <div className="summary-item" key={item.slug}><div className="summary-image"><img src={item.image} alt=""/><span>{item.quantity}</span></div><div><strong>{ar?(p?.arName||item.name):(p?.name||item.name)}</strong><small>{ar?'اللون':'Color'}: {ar?(item.arColor||p?.arColor):(item.color||p?.color)}</small><small>{ar?'المقاس':'Size'}: {item.size||'-'}</small></div><b>EGP {(item.price*item.quantity).toFixed(2)}</b></div>})}</div>}<div className="costs"><div><span>{ar?'الإجمالي':'Total'}</span><b>EGP {subtotal.toFixed(2)}</b></div></div></div></aside></main>;
}
