'use client';
import { useEffect, useState } from 'react';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { products } from '../../../lib-products';

const WHATSAPP_NUMBER = '201069473693';

type CartItem = { slug:string; name:string; image:string; price:number; quantity:number; color:string; arColor:string; size?:string };

export default function ProductPage({ params }: { params: { slug: string } }) {
 const product = products.find(p => p.slug === params.slug); if (!product) return notFound();
 const [language,setLanguage]=useState<'en'|'ar'>('en');
 const [size,setSize]=useState(product.sizeOptions[0]);
 const [weight,setWeight]=useState('');
 const [added,setAdded]=useState(false);
 const ar=language==='ar';
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=ar?'rtl':'ltr';},[language,ar]);
 function addToCart(){try{const current=JSON.parse(localStorage.getItem('saffa-cart')||'[]') as CartItem[];const found=current.find(item=>item.slug===product.slug);const next=found?current.map(item=>item.slug===product.slug?{...item,quantity:item.quantity+1,size}:item):[...current,{slug:product.slug,name:product.name,image:product.image,price:product.price,quantity:1,color:product.color,arColor:product.arColor,size}];localStorage.setItem('saffa-cart',JSON.stringify(next));setAdded(true);}catch{}}
 function order(){const sizeInfo=product.sizeInfo[size]||'';const message=ar?`مرحباً صفا فاشن 👋\n\nأرغب في طلب:\n\nالمنتج: ${product.arName}\nاللون: ${product.arColor}\nالسعر: ${product.price} جنيه مصري${product.originalPrice?`\nالسعر قبل الخصم: ${product.originalPrice} جنيه مصري\nالعرض: ${product.saleLabel}`:''}\nالمقاس: ${size} (${sizeInfo})\nالوزن: ${weight||'غير محدد'} kg\n\nمتاح المعاينة قبل الاستلام. يرجى تأكيد التوفر والتوصيل.`:`Hello Saffa Fashion 👋\n\nI would like to order:\n\nProduct: ${product.name}\nColor: ${product.color}\nPrice: EGP ${product.price.toFixed(2)}${product.originalPrice?`\nOriginal price: EGP ${product.originalPrice.toFixed(2)}\nOffer: ${product.saleLabel}`:''}\nSize: ${size} (${sizeInfo})\nWeight: ${weight||'Not provided'} kg\n\nPlease confirm availability and delivery. Inspection before receipt is requested.`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
 return <main className="detail"><div className="container"><div className="detail-grid"><div className="detail-image"><img src={product.image} alt={product.name}/></div><div><div className="kicker">SAFFA FASHION · {ar?product.arColor:product.color}</div><div style={{display:'flex',gap:8,marginBottom:18}}><button type="button" onClick={()=>setLanguage('en')} className={ar?'btn btn-light':'btn'}>English</button><button type="button" onClick={()=>setLanguage('ar')} className={ar?'btn':'btn btn-light'}>العربية</button></div><h1 className="serif">{ar?product.arName:product.name}</h1><div className="detail-ar">{ar?product.name:product.arName}</div><div style={{fontSize:22,fontWeight:700,margin:'18px 0'}}>EGP {product.price.toFixed(2)} {product.originalPrice&&<del style={{fontSize:14,color:'#888',marginInlineStart:10}}>EGP {product.originalPrice.toFixed(2)}</del>}</div>{product.saleLabel&&<div style={{fontWeight:800,letterSpacing:'.12em',fontSize:11,marginBottom:18}}>{product.saleLabel}</div>}<p className="desc">{ar?product.arDescription:product.description}</p>{product.material&&<p className="shipping-note">{ar?product.arMaterial:product.material}</p>}<div className="option-label">{ar?'المقاس':'Size'}</div><div className="size-row">{product.sizeOptions.map(s=><button key={s} onClick={()=>setSize(s)} className={`size-btn ${size===s?'active':''}`}><strong>{s}</strong><br/><small>{product.sizeInfo[s]}</small></button>)}</div><label className="option-label" htmlFor="weight">{ar?'الوزن':'Weight'} <small>({ar?'اختياري':'optional'})</small></label><input id="weight" value={weight} onChange={e=>setWeight(e.target.value)} placeholder={ar?'مثال: 68 كجم':'e.g. 68 kg'} style={{width:'100%',padding:'14px 16px',border:'1px solid var(--line)',borderRadius:14,background:'#fff'}}/><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><button className="btn" onClick={addToCart}>🛒 {added?(ar?'تمت الإضافة':'Added to Cart'):(ar?'أضف إلى السلة':'Add to Cart')}</button><button className="btn btn-light" onClick={order}>💬 {ar?'اطلب عبر واتساب':'Buy Now'}</button><Link href="/cart" className="btn btn-light">{ar?'عرض السلة':'View Cart'} →</Link></div><p className="shipping-note">{ar?'متاح المعاينة قبل الاستلام · الدفع يتم كديبوزيت بعد تأكيد الطلب على واتساب.':'Inspection before receipt is available. Deposit/payment details are confirmed with you on WhatsApp.'}</p></div></div></div></main>;
}
